data:
  image_directory: ../../resources/kyobobook-images/
  quantized_index: ../../resources/kyobobook-quantized.index
  quantized_images: ../../resources/kyobobook-quantized.npy
  image_size: 384
  validation_ratio: 0.01

model:
  decoder:
    vocab_size: 16384
    hidden_size: 512
    num_hidden_layers: 8
    num_attention_heads: 8
    intermediate_size: 2048
    max_position_embeddings: 576
    layer_norm_eps: 1e-5
    num_labels: 768
  discriminator:
    num_channels: 3
    base_dim: 256
    max_hidden_dim: 2048
    middle_reduction: 4
    num_blocks: 5
    num_layers_in_block: 2
  perceptual:
    input_size: [192, 192]
    language: ["ko"]

optim:
  optimizer:
    lr: 1e-4
    betas: [0.9, 0.99]
    eps: 1e-6
    weight_decay: 1e-4
  scheduler:
    name: constant_with_warmup
    num_warmup_steps: 0
  criterion:
    l2_recon: 1.0
    l1_recon: 0.1
    perceptual: 0.1
    adversarial: 0.01
  num_discriminator_steps: 1

train:
  name: vqgan-f16-vit-small
  epochs: 100
  batch_size: 128
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  validation_interval: 1.0
  log_every_n_steps: 10
