dataset:
  filename: ../../resources/kyobobook-dataset.jsonl
  image_dir: ../../resources/kyobobook-images
  image_size: 128
  dataloader_workers: -1

model:
  generator:
    num_labels: 316
    latent_dim: 128
    embedding_dim: 128
    hidden_dims: [1024, 1024, 1024, 512, 512, 256, 256, 128, 128, 64]
    use_grad_ckpt: false
  discriminator:
    num_labels: 316
    hidden_dims: [128, 128, 256, 256, 512, 512, 1024, 1024, 1024, 1024]
    attn_position: 1
    use_grad_ckpt: false
  truncation: 0.5

optim:
  generator:
    lr: 5e-5
    betas: [0, 0.999]
    eps: 1e-6
  discriminator:
    lr: 2e-4
    betas: [0, 0.999]
    eps: 1e-6
  generator_ema:
    decay: 0.9999
    start_after: 10000
  num_discriminator_steps: 2
  num_standing_stats: 100

train:
  name: biggan-deep-128-small
  steps: 100000
  batch_size: 128
  accumulate_grads: 2
  validation_interval: 1
  precision: 16
  gpus: 1