data:
  book_dataset: ../../resources/kyobobook-dataset.jsonl
  image_dataset: ../../resources/kyobobook-quantized.csv
  text_max_length: 64
  validation_ratio: 0.01

model:
  vqgan: vqgan-decoder.pth
  encoder: klue/roberta-large
  decoder:
    add_cross_attention: true
    activation_function: gelu
    bos_token_id: 8192
    eos_token_id: 8192
    initializer_range: 0.02
    n_embd: 512
    n_head: 8
    n_layer: 6
    vocab_size: 8193
  generation:
    max_length: 577
    min_length: 577
    do_sample: true
    temperature: 1.0
    top_k: 50

optim:
  encoder:
    lr: 3e-5
    betas: [0.9, 0.999]
    eps: 1e-6
    weight_decay: 0.01
  decoder:
    lr: 3e-4
    betas: [0.9, 0.999]
    eps: 1e-6
    weight_decay: 0.01
  scheduler:
    name: linear
    num_warmup_steps: 0
    num_training_steps: 500000

train:
  name: dalle-klue-roberta-large
  batch_size: 96
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  validation_interval: 1.0
  log_every_n_steps: 10
