data:
  book_dataset: ../../resources/kyobobook-dataset.jsonl
  image_dataset:
    index: ../../resources/kyobobook-quantized.index
    filenames:
    - ../../resources/kyobobook-quantized.npy
    - ../../resources/kyobobook-quantized-augmentation1.npy
    - ../../resources/kyobobook-quantized-augmentation2.npy
    - ../../resources/kyobobook-quantized-augmentation3.npy
  text_max_length: 64
  validation_ratio: 0.01

model:
  vqgan: vqgan-decoder.pth
  encoder: klue/roberta-large
  decoder:
    add_cross_attention: true
    activation_function: gelu
    bos_token_id: 16384
    eos_token_id: 16384
    initializer_range: 0.02
    n_embd: 1024
    n_head: 16
    n_layer: 16
    vocab_size: 16385
  generation:
    max_length: 577
    min_length: 577
    do_sample: true
    temperature: 1.0
    top_k: 50

optim:
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.01
  scheduler:
    name: linear
    num_warmup_steps: 10000
    num_training_steps: 1000000

train:
  name: dalle-16l-1024d
  batch_size: 64
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  validation_interval: 1.0
  log_every_n_steps: 10
